name: Weekly Trending Snippet Post

on:
  schedule:
    - cron: "0 0 * * 0" # Run at midnight every Sunday
  workflow_dispatch: # Allow manual trigger

jobs:
  post-trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install Dependencies
        run: bun install
        
      - name: Run Autoposter Script
        run: bun run src/index.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
